name: sistema_estagio
description: Sistema de GestÃ£o de EstÃ¡gios e Aprendizagem

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado e navegaÃ§Ã£o
  provider: ^6.0.5
  go_router: ^12.0.0

  open_filex: ^4.7.0

  fl_chart: ^0.68.0
 

  # HTTP e dados
  http: ^1.1.0
  dio: ^5.3.2
  shared_preferences: ^2.2.2

  # UI
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.5.0

  # FormulÃ¡rios e validaÃ§Ã£o
  form_field_validator: ^1.1.0
  mask_text_input_formatter: ^2.5.0
  flutter_quill: ^10.0.0
  flutter_quill_extensions: ^10.0.0
  vsc_quill_delta_to_html: ^1.0.5
  quill_native_bridge: ^11.0.1
  pdf: ^3.10.8
  html: ^0.15.4
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.3

  # Exportar
  csv: ^6.0.0
  excel: ^4.0.2
  syncfusion_flutter_xlsio: ^27.1.48   # ðŸ‘ˆ aqui alinhado certinho

  # Para salvar/compartilhar em mobile/desktop:
  path_provider: ^2.1.3
  share_plus: ^11.1.0

  # UtilitÃ¡rios
  intl: ^0.19.0
  url_launcher: ^6.1.14
  file_picker: ^8.0.0+1
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.4.1+1
  flutter_multi_formatter: ^2.13.7
  flutter_masked_text2: ^0.9.1
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo_cide.png
    - assets/quem_somos_fotos.png
    - assets/ckeditor.html    
    - assets/ckeditor/    
    - assets/index.html
    - assets/ckeditor/ckeditorfull.js
    - assets/images/logo_acervus.png

